import logging
import os
import re
import tempfile
from pathlib import Path

# --- Application Configuration ---
# Environment-backed settings with sensible defaults
def _env_int(name: str, default: int) -> int:
    """Read an int from the environment, falling back on anything unparseable.

    These run at import time, so a typo in one env var used to abort the whole
    process with a bare ValueError and no indication of which setting was wrong.
    """
    raw = os.environ.get(name)
    if raw is None or str(raw).strip() == "":
        return default
    try:
        return int(str(raw).strip())
    except ValueError:
        logging.getLogger(__name__).warning(
            "%s=%r is not a whole number; using the default %d.", name, raw, default
        )
        return default


def _env_float(name: str, default: float) -> float:
    raw = os.environ.get(name)
    if raw is None or str(raw).strip() == "":
        return default
    try:
        return float(str(raw).strip())
    except ValueError:
        logging.getLogger(__name__).warning(
            "%s=%r is not a number; using the default %s.", name, raw, default
        )
        return default


LOG_LEVEL = os.environ.get("LOG_LEVEL", "INFO").upper()
FLASK_SECRET_KEY = os.environ.get("FLASK_SECRET_KEY", "dev-secret")
SESSION_TTL_HOURS = _env_int("SESSION_TTL_HOURS", 48)

# Bundle / ZIP import limits (uncompressed totals; defense-in-depth)
ZIP_MAX_UNCOMPRESSED_BYTES = _env_int("ZIP_MAX_UNCOMPRESSED_BYTES", 200 * 1024 * 1024)
ZIP_MAX_FILES = _env_int("ZIP_MAX_FILES", 5000)

# --- Pandoc Version Policy ---
# Pinned "known-good" Pandoc version. The app does not auto-upgrade; it only
# warns when the installed binary is older than this or when a newer upstream
# release exists. Bump this value when you intentionally adopt a new release.
PANDOC_PINNED_VERSION = os.environ.get("PANDOC_PINNED_VERSION", "3.9.0.2")

# Set to "0" to disable the one-shot GitHub release lookup at startup.
PANDOC_UPDATE_CHECK_ENABLED = os.environ.get("PANDOC_UPDATE_CHECK_ENABLED", "1") not in ("0", "false", "False", "")

# How long a successful update check is cached before the app will re-query
# GitHub. Default: 7 days.
PANDOC_UPDATE_CHECK_TTL_HOURS = _env_int("PANDOC_UPDATE_CHECK_TTL_HOURS", 168)

# Network timeout for the update check. Startup never waits longer than this.
PANDOC_UPDATE_CHECK_TIMEOUT_SECONDS = _env_float("PANDOC_UPDATE_CHECK_TIMEOUT_SECONDS", 3.0)

# --- Path Configuration ---
# All paths resolve under a single PERSIST_DIR
PERSIST_DIR = Path(os.environ.get("PERSIST_DIR", tempfile.gettempdir())) / "docx2html_wsumanual"
PERSIST_DIR.mkdir(parents=True, exist_ok=True)

# Centralized location for reference templates (relative to app root)
REFERENCE_DIR = Path(__file__).parent / "reference_docs"

# Cache file for the last-known-latest Pandoc version (GitHub lookup).
PANDOC_UPDATE_CACHE_PATH = PERSIST_DIR / "pandoc_update_cache.json"

# --- Session Isolation Helper ---
# Session IDs and download tokens are always str(uuid.uuid4()) generated by the
# app itself, so anything else arriving in a URL or form is hostile or stale.
# The version nibble (`4`) and variant nibble (`8`/`9`/`a`/`b`) are enforced so
# only genuine v4 UUIDs pass — not any UUID-shaped string.
_UUID4_RE = re.compile(
    r"^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
)


def is_valid_session_id(value: str) -> bool:
    """True if `value` is a canonical lowercase UUID4 string."""
    return bool(_UUID4_RE.fullmatch(str(value)))


class SessionDir:
    """
    Manages a single session's isolated directory and paths.
    Ensures that filenames are never used as raw path components to avoid collisions.

    Lookup is read-only by default; pass create=True only when starting a new
    session so that probing an unknown/expired ID never writes to disk.
    """
    def __init__(self, session_id: str, create: bool = False):
        self.session_id = str(session_id)
        if not is_valid_session_id(self.session_id):
            raise ValueError(f"Invalid session id: {self.session_id!r}")
        self.root = PERSIST_DIR / self.session_id
        self.export_dir = self.root / "export"
        if create:
            self.root.mkdir(parents=True, exist_ok=True)
            self.export_dir.mkdir(parents=True, exist_ok=True)

    @property
    def source_docx(self) -> Path:
        """The original uploaded DOCX file."""
        return self.root / "source.docx"

    @property
    def pre_docx(self) -> Path:
        """The preprocessed DOCX ready for Pandoc."""
        return self.root / "source.pre.docx"

    @property
    def temp_html(self) -> Path:
        """The raw Pandoc output HTML."""
        return self.root / "source.temp.html"

    @property
    def edits_json(self) -> Path:
        """Manual reference and link overrides."""
        return self.root / "edits.json"

    @property
    def stable_map_json(self) -> Path:
        """The canonical signature-to-ID permalink artifact."""
        return self.root / "stable_heading_map.json"

    @property
    def manifest_json(self) -> Path:
        """The session state and metadata (manifest.json)."""
        return self.root / "manifest.json"

    @property
    def export_html(self) -> Path:
        """The final formatted HTML output."""
        return self.export_dir / "output.html"

    @property
    def export_docx(self) -> Path:
        """The final plain-Pandoc DOCX output."""
        return self.export_dir / "output.docx"

    @property
    def session_json(self) -> Path:
        """The primary session state file within the isolated session directory."""
        return self.root / "session.json"

    def exists(self) -> bool:
        return self.root.exists()

    def __repr__(self):
        return f"<SessionDir {self.session_id} at {self.root}>"
